# Generated by Django 4.2.1 on 2023-05-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitalapp', '0004_watchmen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmen',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
