# Generated by Django 4.2.1 on 2023-05-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Digitalapp', '0006_delete_events_delete_notice_delete_societysecretory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_des', models.CharField(max_length=200)),
                ('event_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=100)),
                ('notice_des', models.CharField(max_length=100)),
                ('notice_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocietySecretory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, default='123', max_length=100, null=True)),
                ('picture', models.FileField(default='sad.jpg', upload_to='secretory.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='Watchmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchmen_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, default='123', max_length=100, null=True)),
                ('watchman_picture', models.FileField(default='sad.jpg', upload_to='watchman.jpg')),
            ],
        ),
        migrations.AddField(
            model_name='societymembers',
            name='password',
            field=models.CharField(blank=True, default='123', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=100)),
                ('v_contact', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Digitalapp.societymembers')),
            ],
        ),
    ]
